headers = superblock.h fragment_descriptor.h file_descriptor.h config.h \
	file_descriptor_node.h free_space_node.h

install:
	mkdir -p $(DESTDIR)/usr/include/EFS
	cp $(headers) $(DESTDIR)/usr/include/EFS
